
import { Country } from '../types';

export const COUNTRIES: Country[] = [
  { code: 'in', name: 'India' },
  { code: 'us', name: 'USA' },
  { code: 'br', name: 'Brazil' },
  { code: 'jp', name: 'Japan' },
  { code: 'de', name: 'Germany' },
  { code: 'fr', name: 'France' },
  { code: 'gb', name: 'UK' },
  { code: 'au', name: 'Australia' },
  { code: 'ca', name: 'Canada' },
  { code: 'ar', name: 'Argentina' },
  { code: 'kr', name: 'South Korea' },
  { code: 'es', name: 'Spain' },
  { code: 'it', name: 'Italy' },
  { code: 'mx', name: 'Mexico' },
  { code: 'cn', name: 'China' },
  { code: 'ru', name: 'Russia' },
  { code: 'sa', name: 'Saudi Arabia' },
  { code: 'za', name: 'South Africa' },
  { code: 'tr', name: 'Turkey' },
  { code: 'eg', name: 'Egypt' },
  { code: 'nl', name: 'Netherlands' },
  { code: 'ch', name: 'Switzerland' },
  { code: 'se', name: 'Sweden' },
  { code: 'no', name: 'Norway' },
  { code: 'id', name: 'Indonesia' },
  { code: 'ph', name: 'Philippines' },
  { code: 'vn', name: 'Vietnam' },
  { code: 'th', name: 'Thailand' },
  { code: 'pt', name: 'Portugal' },
  { code: 'gr', name: 'Greece' },
  { code: 'pk', name: 'Pakistan' },
  { code: 'bd', name: 'Bangladesh' },
  { code: 'ng', name: 'Nigeria' },
  { code: 'co', name: 'Colombia' },
  { code: 'cl', name: 'Chile' },
  { code: 'be', name: 'Belgium' },
  { code: 'pl', name: 'Poland' },
  { code: 'ua', name: 'Ukraine' },
  { code: 'ae', name: 'UAE' },
  { code: 'nz', name: 'New Zealand' },
  { code: 'ie', name: 'Ireland' },
  { code: 'at', name: 'Austria' },
  { code: 'sg', name: 'Singapore' },
  { code: 'my', name: 'Malaysia' },
  { code: 'dk', name: 'Denmark' },
  { code: 'fi', name: 'Finland' },
  { code: 'cz', name: 'Czech Republic' },
  { code: 'hu', name: 'Hungary' },
  { code: 'ro', name: 'Romania' },
  { code: 'hr', name: 'Croatia' },
  { code: 'rs', name: 'Serbia' },
  { code: 'bg', name: 'Bulgaria' },
  { code: 'sk', name: 'Slovakia' },
  { code: 'il', name: 'Israel' },
  { code: 'ir', name: 'Iran' },
  { code: 'iq', name: 'Iraq' },
  { code: 'qa', name: 'Qatar' },
  { code: 'ma', name: 'Morocco' },
  { code: 'ke', name: 'Kenya' },
  { code: 'gh', name: 'Ghana' },
  { code: 'pe', name: 'Peru' },
  { code: 've', name: 'Venezuela' },
  { code: 'cu', name: 'Cuba' },
  { code: 'jm', name: 'Jamaica' },
  { code: 'dz', name: 'Algeria' },
  { code: 'et', name: 'Ethiopia' },
  { code: 'tz', name: 'Tanzania' },
  { code: 'ug', name: 'Uganda' },
  { code: 'sn', name: 'Senegal' },
  { code: 'ci', name: 'Ivory Coast' },
  { code: 'cm', name: 'Cameroon' },
  { code: 'ao', name: 'Angola' },
  { code: 'uz', name: 'Uzbekistan' },
  { code: 'kz', name: 'Kazakhstan' },
  { code: 'lk', name: 'Sri Lanka' },
  { code: 'np', name: 'Nepal' },
  { code: 'mm', name: 'Myanmar' },
  { code: 'kh', name: 'Cambodia' },
  { code: 'la', name: 'Laos' },
  { code: 'mn', name: 'Mongolia' },
  { code: 'jo', name: 'Jordan' },
  { code: 'lb', name: 'Lebanon' },
  { code: 'om', name: 'Oman' },
  { code: 'kw', name: 'Kuwait' }
];
